### ISSUE TITLE
Warning after purchasing Field Types Pack

### ISSUE THREAD

**Issue by vladkucherov** [michaeluno/admin-page-framework#191]
Hi,

I get the warning:
> Strict Standards: Declaration of EDDSoftwareLicensingCustomFieldType::doOnFieldRegistration() should be compatible with AdminPageFramework_FieldType::doOnFieldRegistration(array $aField) in /home/***/wp-content/plugins/admin-page-framework-field-type-pack/include/library/cutom-field-types/edd-software-licensing/EDDSoftwareLicensingCustomFieldType.php on line 3

In this case you should change from (``Line 108``):
```php
protected function doOnFieldRegistration( $aField ) {
```
to:
```php
protected function doOnFieldRegistration( array $aField ) {
```

Also I wanted to know how I should receive updates ?

**Comment by michaeluno** [comment]
Thanks for the report.

I see. I think the type hinting in the `doOnFieldRegistration()` method parameter in the `AdminPageFramework_FieldTyp` class should be dropped because the method is meant to be used by framework users who write own custom field types. And this kind of mistake is easy to make. 

> Also I wanted to know how I should receive updates ?

Go to `Dashboard` -> `Admin Page Framework` -> `Field Type Pack` and then enter your license key printed on the purchase receipt. If you successfully activate the license, you'll get updates. One way to test it to manually decrease the version number of the add on.

**Comment by michaeluno** [comment]
v3.5.1.1 has been released which fixes this issue.
