### ISSUE TITLE
Help with custom field type

### ISSUE THREAD

**Issue by baskettcase** [michaeluno/admin-page-framework#199]
Hey Michael, me again :) I could really use some help with another custom field type. This is the regular code, but I need it repeatable and sortable, which is why I need it to be a custom field type correct? I've done several custom ones since you helped me last time, but this one is more difficult since a couple of the fields have multiple dropdowns and the custom one that you did that I've been referencing only has input fields and textboxes. Any help would be appreciated! thanks!  

```php
if ( include( FPP_APF_FIELD_TYPES. 'FPPImage.php' ) ) {
	new FPPImageFieldType( get_class( $this ) );
}

$rotate_dropdown = array();
for ($i=-10; $i<=10; $i++) $rotate_dropdown[$i] = $i .'&deg;';
$pos_dropdown = array(
	'none' => 'None',
	'topleft' => 'Top Left',
	'topmid' => 'Top Middle',
	'topright' => 'Top Right',
	'midleft' => 'Middle Left',
	'midright' => 'Middle Right',
	'botleft' => 'Bottom Left',
	'botmid' => 'Bottom Middle',
	'botright' => 'Bottom Right'
);
$tape_rotate_dropdown = array(
	'0' => '0&deg;',
	'45' => '45&deg;',
	'90' => '90&deg;',
	'-45' => '-45&deg;'
);

$oAdminPage->addSettingFields(
	#'_default',
	array(
		'field_id'	=> 'image',
		'title'		=> 'Image',
		'type'	=> 'image'
	),
	array(
		'field_id'	=> 'rotate',
		'title'		=> 'Image Rotation',
		'type'	=> 'select',
		'label'       => $rotate_dropdown,
		'default'   => 0
	),
	array(
		'field_id'	=> 'first_tape',
		'title'		=> 'Tape 1',
		'type'	=> 'select',
		'before_input' => 'Tape Position &nbsp;',
		'label'       => $pos_dropdown,
		'attributes'    => array(
			'field'	=> array(
				'style' => 'display: inline; clear: none',
			),
		),
		array(
			'before_input' => '&nbsp; Tape Rotation &nbsp; ',
			'label'	=> $tape_rotate_dropdown
		)
	),
	array(
		'field_id'	=> 'second_tape',
		'title'		=> 'Tape 2',
		'type'	=> 'select',
		'before_input' => 'Tape Position &nbsp;',
		'label'     => $pos_dropdown,
		'attributes'    => array(
			'field'	=> array(
				'style' => 'display: inline; clear: none',
			),
		),
		array(
			'before_input' => '&nbsp; Tape Rotation &nbsp; ',
			'label'	=> $tape_rotate_dropdown
		)
	)
);
```

**Comment by michaeluno** [comment]
Hey Rick,

Can you fix the markdown in your post?  You can use triple back-tics followed by a language name like this.

    ```php
    your code here
    ```
(https://help.github.com/articles/github-flavored-markdown/)

**Comment by baskettcase** [comment]
There you go, sorry about that. I didn't notice that it had modified it :)

**Comment by michaeluno** [comment]
So are you trying to create a field type that contains one `image` and three `select` field types which can be sortable and repeatable?

**Comment by baskettcase** [comment]
Well one image and five selects, like this image: http://awesomescreenshot.com/01b4efvh9e

**Comment by michaeluno** [comment]
I've posted an example plugin on Gist. https://gist.github.com/michaeluno/bb1b9a71d3d992981972

Hope it helps.

**Comment by baskettcase** [comment]
Awesome, thank you! Ill give it a try and see how it goes. After this one Ill probably be able to reference your code for pretty much anything else related to custom field types :)

**Comment by michaeluno** [comment]
@baskettcase So is it working? I've noticed a few issues with the current implementation of the framework when I wrote the custom field type. 
- image field type is not extending `AdminPageFramework_FieldType`
- a field definition array needs to be passed to the ` AdminPageFramework_Input_select` class. 

Regarding the second issue, currently it is required to modify the field definition array to create sub-fields and the field definition array contains some internal system arguments. So rather than creating an input object with a field definition array, I thought it would be better with an attributes array.

I've already changed the input classes to accept attribute array from field definition array in the 3.5.3b branch. I'm going to update the posted example plugin to follow that change. However, it will not be compatible with 3.5.2 or below.

**Comment by baskettcase** [comment]
I was able to test it today and with some tweaks I should be able to get it to look the way I want. I like that I can easily add another select box in there so that there were five, very nice. It doesn't look like I need the new version of the class yet since it's working? or are you saying that the settingFields would change with the 3.5.3 that you're talking about?

**Comment by baskettcase** [comment]
Is there a way to add the labels that I show in the previous screenshot? Since labels are used for the dropdown values and before_input doesn't seem to work within the select_fields array (which makes sense). Or should I just add them within the fieldtype itself? Although since the select fields are flexible and I can add as many as I want, then maybe that wouldn't work. Ill keep playing with it and see what I can come up with.

**Comment by baskettcase** [comment]
Im also seeing that the repeat plus sign that duplicates is right next to the image field instead of at the bottom right. Im not sure if that is a stylesheet thing, or if it's in the code (I can't seem to find it in the code... yet) Ill keep looking. I thought I would throw that out there just incase it's a bit more involved and not straightforward like most of the code.

**Comment by michaeluno** [comment]
> It doesn't look like I need the new version of the class yet since it's working? or are you saying that the settingFields would change with the 3.5.3 that you're talking about?

The current posted example plugin above will/should be compatible with v3.5.2 or below but the one I'm going to update and post will not.

> Is there a way to add the labels that I show in the previous screenshot?

Modify the `_getSelectFieldsOutput()` method in the example plugin. In that method, you see it parses the `select_fields` argument. In that loop, embed your custom output with your preferred custom. And in the `addSettingFields()` method when you define form fields, add your custom argument with your preferred labels.

> It doesn't look like I can add in custom styles? I was trying to see if I could access the parent's parent class to add custom styles using getStyles(), but it doesn't look like Im able to do that. How would I add in custom styles like I can with the other fieldtypes?

Overriding `getStyles()` is not working because the `image` field type is not extending `AdminPageFramework_FieldType` but `AdminPageFramework_FieldType_Base` which is what I said in the last reply. It has been fixed in v3.5.3b. You can override `_replyToGetStyles()` method instead or try the 3.5.3b development branch.

**Comment by baskettcase** [comment]
Ok Ill try the 3.5.3b and see what happens.

**Comment by michaeluno** [comment]
Updated the example plugin posted above. 

I'm closing this topic. If you still have a problem, let me know.

**Comment by baskettcase** [comment]
Thanks Michael, did you get the paypal thanks?

**Comment by michaeluno** [comment]
Yes, thanks for the donation!
