### ISSUE TITLE
Duplicated fields

### ISSUE THREAD

**Issue by vladkucherov** [michaeluno/admin-page-framework#215]
Good day,

I have a network of websites that uses APF Post Type.
I added some metaboxes with ACE editor field type.

for some reason, only on one of my websites (there are about 7) the field is duplicated
![image](https://cloud.githubusercontent.com/assets/4151984/8771370/82651a7e-2ec9-11e5-9d84-c594adc9153b.png)

I looked in the source, and the textarea is not duplicated, but, if I look in the Google Chrome Inspect, I can see that it is.

![image](https://cloud.githubusercontent.com/assets/4151984/8771387/bd07d162-2ec9-11e5-9491-0f61856d1c31.png)

Any Ideas?

**Comment by michaeluno** [comment]
Hello,

You may try disabling the browser JavaScript. There is an Chrome extension to toggle JavaScript. (https://chrome.google.com/webstore/detail/quick-javascript-switcher/geddoclleiomckbhadiaipdggiiccfje)

If the field does not get duplicated when you disable JavaScript in the browser, it is most likely caused by the script of the field type.

**Comment by michaeluno** [comment]
Closing the topic due to inactivity.
