### ISSUE TITLE
Calls to classes that do not exist?

### ISSUE THREAD

**Issue by xarkitu** [michaeluno/admin-page-framework#220]
Hi,

Use this utility to debug my classes -> https://wordpress.org/plugins/query-monitor/

The case is that when I check procedure calls or hooks, I always find errors invalid calls in the framework base and compiled for my plugin.

If you are not using this utility, I suggest you take a look, it is useful for debugging calls and some things wrong we will head when we're messing code.

Sorry for my English, I am not native and try to express clearly.

The most common errors are:

AdminPageFrameworkLoader_AdminPageWelcome->start_AdminPageFrameworkLoader_AdminPageWelcome()
Error: Method AdminPageFrameworkLoader_AdminPageWelcome::start_AdminPageFrameworkLoader_AdminPageWelcome() does not exist

AdminPageFrameworkLoader_AdminPage->start_AdminPageFrameworkLoader_AdminPage()
Error: Method AdminPageFrameworkLoader_AdminPage::start_AdminPageFrameworkLoader_AdminPage() does not exist

AdminPageFrameworkLoader_AdminPageWelcome->setup_pre()
Error: Method AdminPageFrameworkLoader_AdminPageWelcome::setup_pre() does not exist

AdminPageFrameworkLoader_AdminPage->setup_pre()
Error: Method AdminPageFrameworkLoader_AdminPage::setup_pre() does not exist

AdminPageFrameworkLoader_AdminPageWelcome->set_up_AdminPageFrameworkLoader_AdminPageWelcome()
Error: Method AdminPageFrameworkLoader_AdminPageWelcome::set_up_AdminPageFrameworkLoader_AdminPageWelcome() does not exist

AdminPageFrameworkLoader_AdminPage->set_up_AdminPageFrameworkLoader_AdminPage()
Error: Method AdminPageFrameworkLoader_AdminPage::set_up_AdminPageFrameworkLoader_AdminPage() does not exist

**Comment by michaeluno** [comment]
Looks like function calls of framework dynamic hooks such as `start_{...}()` and `set_up_{....}()` are reported. Probably it is because the framework uses the `__call()` overload magic method to support dynamic hook names. So don't worry about the errors. 

Indeed, it may be difficult to differentiate from real errors. For that, you may ask the developer of that plugin to add an option to ignore errors caused by calling undefined methods which are handled in `__call()`.
