### ISSUE TITLE
Empty generated ZIP

### ISSUE THREAD

**Issue by szepeviktor** [michaeluno/admin-page-framework#235]
WIth version 3.7.11 and vanilla WP I get an ZIP with an empyt `""` named folder.
[us-unlocked-admin-page-framework.3.7.11-3.zip](https://github.com/michaeluno/admin-page-framework/files/134142/us-unlocked-admin-page-framework.3.7.11-3.zip)

**Comment by szepeviktor** [comment]
Only 7-Zip opens it.

**Comment by michaeluno** [comment]
I could confirm the problem. It seems it only occurs on Windows. Thanks for the report. 

The `AdminPageFramework_Zip` class is used to generate a zip file. Would be appreciated if you could play around with the class and create a zip file in your environment to see if you can open it.

**Comment by szepeviktor** [comment]
WP has PclZip built in. Could you use that?

**Comment by michaeluno** [comment]
Sounds like a good option. 

If you have a chance to see if it can be used instead of the framework zip utility class, you want to modify this class method, `_getDownloadFrameworkZipFile()` ( https://github.com/michaeluno/admin-page-framework/blob/3.7.11/include/class/admin/admin-page-framework/tool/generator/AdminPageFrameworkLoader_AdminPage_Tool_Generator_Generator.php#L263-L287).

**Comment by szepeviktor** [comment]
PclZip in much simpler but please consider using it because it is a WP built-in class.

**Comment by michaeluno** [comment]
I'm going to leave it as it works now. Not sure in what sense it is simpler but if you are interested, you are always welcome to suggest better code. The class method to modify is mentioned in the previous reply.
