### ISSUE TITLE
Zip file access from windows

### ISSUE THREAD

**Issue by mgibellini** [michaeluno/admin-page-framework#252]
I cannot Open Zip file on Windows.

I solved the problem adding this code:

ob_clean();

on line 34 of AdminPageFramework_Zip.php file

**Comment by michaeluno** [comment]
Hi,

I cannot confirm the problem in my environment. However, by searching the web for similar issues, it does not seem to be uncommon. 

- https://core.trac.wordpress.org/ticket/14730
- https://wordpress.org/support/topic/zip-file-is-corrupt-after-download
- http://stackoverflow.com/questions/23447331/php-how-to-properly-serve-file-download-using-readfile-with-output-buffering-co/23447332#23447332

It could be that your server is printing some kind of an error message during the download process and causes the file to corrupt. Instead of modifying `AdminPageFramework_Zip`, can you try modifing the `replyToDownloadFramework()` method of the `AdminPageFrameworkLoader_AdminPage_Tool_Generator_Generator` class?

Around the line [252](
https://github.com/michaeluno/admin-page-framework/blob/3.7.14/include/class/admin/admin-page-framework/tool/generator/AdminPageFrameworkLoader_AdminPage_Tool_Generator_Generator.php#L252), change this 

```php
        header( "Content-Length: " . strlen( $_sData ) );
        unlink( $_sTempFile );
```
to
```php        
        unlink( $_sTempFile );   
        header( "Content-Length: " . strlen( $_sData ) );
        ob_clean();   
        flush();         
```

Let me know if this works.

**Comment by michaeluno** [comment]
Closing the topic due to inactivity.
