### ISSUE TITLE
General Comment and Vote

### ISSUE THREAD

**Issue by VR51** [michaeluno/admin-page-framework#269]
Michael, this is just a note to let you know I believe Admin Page Framework needs to be made part of WP Core. I've added a comment to [Make WP](https://make.wordpress.org/core/2017/05/26/media-widgets-for-images-video-and-audio/) to that effect. Hope you don't object. If I remember rightly this framework was first announced on Stack Exchange, seem to remember seeing it there. Hope my suggestion goes where you allow it to go.

**Comment by michaeluno** [comment]
Hey, I'm glad you have a high opinion about this framework. And I appreciate you see the quality of it. You know it might be difficult for them to accept your suggestion because this framework does not follow the [WordPress coding standard](https://make.wordpress.org/core/handbook/best-practices/coding-standards/php/). 

Also, there has been [Fields API](https://make.wordpress.org/core/2016/03/14/fields-api-where-were-at/) which is part of the WordPress core. 

So I hardly see there is room for APF to be taken part in the WordPress code base. I appreciate your view though.

**Comment by VR51** [comment]
I remember fields being mentioned ages ago now that you mention it. Came out of PODs, if I recall rightly, which is a nice framework. Not as easy to use as yours, though. Thanks for replying, Michael.
